## Basic calculation operation

Basic calculation operation using TensorFlow v2 tensors.
- by Muztrizen
- TF Functions: https://www.tensorflow.org/api_docs/python/tf

In [13]:
import tensorflow as tf

In [14]:
# Define tensor constant
a = tf.constant(1)
b = tf.constant(2)
c = tf.constant(3)

### Calculate 2 dimensions tensor

In [15]:
# Define tf functions and elements
add = tf.add(a,b)
sub = tf.subtract(a,b)
mul = tf.multiply(a,b)
div = tf.divide(a,b)

In [16]:
# Access tensors value
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 3
sub = -1
mul = 2
div = 0.5


### Calculate multi dimensions tensor

In [17]:
# Define tf functions and elements
min = tf.reduce_min([a,b,c])
max = tf.reduce_max([a,b,c])
mean = tf.reduce_mean([a,b,c])
prod = tf.reduce_prod([a,b,c])
sum = tf.reduce_sum([a,b,c])

In [18]:
# Access tensors value
print("min =", min.numpy())
print("max =", max.numpy())
print("mean =", mean.numpy())
print("prod =", prod.numpy())
print("sum =", sum.numpy())

min = 1
max = 3
mean = 2
prod = 6
sum = 6


### Calculate matrix tensor

In [19]:
# Define tensor matrix 
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[5.,6.],[7.,8.]])

In [20]:
# Define tf functions and elements
mat_product = tf.matmul(matrix1, matrix2)
mat_product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [21]:
print(mat_product.numpy())

[[19. 22.]
 [43. 50.]]
