In [55]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [56]:
# read dataset
mnist = tf.keras.datasets.mnist

In [57]:
# load and prepare dataset
(x_train, y_train) , (x_test, y_test) = mnist.load_data()

In [58]:
# convert x data from int to floating-pointxtrain
x_train, x_test = x_train / 255.0 , x_test /255.0

In [59]:
# build the sequential model by stacking layers
# choose optimizer for loss function
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [60]:
# model returns a vector of logits or log-odds
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.51274025, -0.2887105 , -0.15718094, -0.05432756,  0.41422468,
        -0.04662386,  0.51590157, -0.09892102,  0.93851864, -0.59553236]],
      dtype=float32)

In [61]:
# convert logits to probabilities ranging from 0~1
#def logistic_regression():
tf.nn.softmax(predictions).numpy()

array([[0.13491832, 0.06053483, 0.06904431, 0.0765238 , 0.1222605 ,
        0.0771156 , 0.13534552, 0.0731863 , 0.20653048, 0.04454042]],
      dtype=float32)

In [62]:
# return a scalar loss
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [63]:
loss_fn(y_train[:1], predictions).numpy()

2.5624497

In [64]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [65]:
# fit model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.5016 - accuracy: 0.8556
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1489 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1136 - accuracy: 0.9661
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0877 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0765 - accuracy: 0.9766


In [66]:
# evaluate model
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0748 - accuracy: 0.9766


[0.07475410401821136, 0.9765999913215637]

In [67]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [68]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.6509523e-07, 3.4442447e-09, 3.4624359e-06, 2.9620106e-04,
        2.9090385e-12, 2.0509704e-07, 3.1034357e-13, 9.9968684e-01,
        9.6800591e-07, 1.1695566e-05],
       [7.2527072e-08, 1.1569866e-04, 9.9977332e-01, 9.3007809e-05,
        5.5481609e-12, 1.7467534e-07, 1.4484851e-07, 2.6404770e-10,
        1.7716655e-05, 5.1279133e-12],
       [1.2844800e-06, 9.9967337e-01, 4.4317861e-05, 2.4665417e-06,
        3.4391964e-05, 9.9158342e-07, 1.2798929e-05, 1.6235524e-04,
        6.7208399e-05, 8.9252256e-07],
       [9.9912399e-01, 4.2033882e-08, 1.5566251e-04, 5.8379783e-07,
        9.8544586e-09, 1.4526945e-05, 6.7143541e-05, 1.8317087e-06,
        2.6501842e-08, 6.3623203e-04],
       [1.3849514e-06, 1.7654508e-09, 1.0597086e-05, 1.7961965e-07,
        9.9453110e-01, 7.6969411e-07, 5.2031382e-06, 2.3319380e-05,
        2.2990921e-06, 5.4252241e-03]], dtype=float32)>